# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Expand environment variable directories
shopt -s direxpand

# Setup general editor environment
export EDITOR="/usr/bin/env emacs -nw"

# Working directories and variables
export DES_REPO=des.opensciencegrid.org
export DES_PATH=/cvmfs/${DES_REPO}

# Commonly used CVMFS commands
alias cvmfs_info="cvmfs_server info ${DES_REPO}"
alias cvmfs_tag="cvmfs_server tag ${DES_REPO}"
alias cvmfs_transaction="cvmfs_server transaction ${DES_REPO}"
alias cvmfs_abort="cd; cvmfs_server abort ${DES_REPO}; cd -"
alias cvmfs_publish="cd; cvmfs_server publish ${DES_REPO}; cd -"

alias transaction=cvmfs_transaction
alias publish=cvmfs_publish
alias screen_publish="cd; screen -S publish -dm cvmfs_server publish ${DES_REPO}; sleep 1s; screen -ls; cd -"

# User specific aliases and functions
alias kadrlica="cd ${DES_PATH}/users/kadrlica"
alias eups_sync="source ${DES_PATH}/users/kadrlica/sync.sh"

# Conda aliases
alias conda_install="source ${HOME}/des-conda/bin/conda_install.sh"
alias conda_pip_install="source ${HOME}/des-conda/bin/conda_pip_install.sh"
alias conda_setup="source ${DES_PATH}/fnal/anaconda2/etc/profile.d/conda.sh"
alias activate="conda activate"
alias deactivate="conda deactivate"